services:
  spinquant:
    build: .
    image: spinquant-image
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    env_file:
      - .env
    volumes:
      - .:/app
      - /home/yardenc/docker-temp/models/rotation:/app/models/rotation
      - /home/yardenc/docker-temp/models/output:/app/output
      - /home/yardenc/docker-temp/models/logs:/app/logs
      - /home/yardenc/docker-temp/models/cache:/app/cache/huggingface

    stdin_open: true
    tty: true
